version: "3.8"

services:
  web:
    build: .
    #command: daphne -b 0.0.0.0 -p 8000 educationplatform.asgi:application
    command: ./manage.py runserver 0.0.0.0:8000
    working_dir: /code/education-platform
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./education-platform
        target: /code/education-platform
      - type: bind
        source: ./media
        target: /opt/media
      - type: volume
        source: static
        target: /opt/static

  smtpd:
    image: python:3.7
    command: python3 -m smtpd -n -c DebuggingServer 0.0.0.0:1025

  celery_worker:
    build: .
    working_dir: /code/education-platform
    command: celery -A educationplatform worker -l info
    volumes:
      - type: bind
        source: ./education-platform
        target: /code/education-platform
    depends_on:
      - rabbitmq
      - web

  celery_beat:
    build: .
    working_dir: /code/education-platform
    command: celery -A educationplatform beat -S django -l info
    volumes:
      - type: bind
        source: ./education-platform
        target: /code/education-platform
    depends_on:
      - rabbitmq
      - web

  rabbitmq:
    image: rabbitmq

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - type: bind
        source: ./media
        target: /opt/media
      - type: volume
        source: static
        target: /opt/static
        volume:
          nocopy: true
    ports:
      - 8080:80

volumes:
  static:
