module.exports = {
	CHANGE_ROOM_LOCK : 'CHANGE_ROOM_LOCK',
	PROMOTE_PEER     : 'PROMOTE_PEER',
	SEND_CHAT        : 'SEND_CHAT',
	MODERATE_CHAT    : 'MODERATE_CHAT',
	SHARE_SCREEN     : 'SHARE_SCREEN',
	EXTRA_VIDEO      : 'EXTRA_VIDEO',
	SHARE_FILE       : 'SHARE_FILE',
	MODERATE_FILES   : 'MODERATE_FILES',
	MODERATE_ROOM    : 'MODERATE_ROOM'
};
